# Generated by Django 4.0.4 on 2022-05-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='non_investment_fulfilled',
            new_name='fulfilled_all',
        ),
        migrations.RemoveField(
            model_name='cashcall',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='cashcall',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='cashcall',
            name='validated',
        ),
        migrations.AddField(
            model_name='bill',
            name='fulfilled_one',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cashcall',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashcall',
            name='sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
